### ISSUE TITLE
broken on python3.10.6

### ISSUE THREAD

**Issue by Alberto247** [capstone-engine/capstone#1930]
When I try importing capstone in my python 3.10.6 environment I get the following error

```
Python 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import capstone
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/capstone/__init__.py", line 267, in <module>
    import pkg_resources
  File "/home/alber/.local/lib/python3.10/site-packages/pkg_resources.py", line 29, in <module>
    import symbol
ModuleNotFoundError: No module named 'symbol'
```

```
python3 -m pip show capstone
Name: capstone
Version: 4.0.2
Summary: Capstone disassembly engine
Home-page: http://www.capstone-engine.org
Author: Nguyen Anh Quynh
Author-email: aquynh@gmail.com
License: UNKNOWN
Location: /usr/local/lib/python3.10/dist-packages
Requires:
Required-by: pwntools, ROPGadget
```

**Comment by XVilka** [comment]
Should be fixed now
