### ISSUE TITLE
segfault in getRegisterName

### ISSUE THREAD

**Issue by Rewzilla** [capstone-engine/capstone#577]
The following crashes capstone while using CS_ARCH_X86/CS_MODE_64...

```
\x6b\x00\x00\x62\xc3\x75\x41\x03\xd0
```

Here's a backtrace...

```
#0  0x00000000004f044a in getRegisterName (RegNo=0x0) at arch/X86/X86GenAsmWriter1.inc:15023
#1  0x00000000004ec426 in printRegName (OS=0x7fffffffdac0, RegNo=0x0) at arch/X86/X86IntelInstPrinter.c:267
#2  0x00000000004ed9f3 in printOperand (MI=0x7fffffffdcd0, OpNo=0x5, O=0x7fffffffdac0) at arch/X86/X86IntelInstPrinter.c:591
#3  0x00000000004f0403 in printInstruction (MI=0x7fffffffdcd0, O=0x7fffffffdac0, MRI=0x988af0) at arch/X86/X86GenAsmWriter1.inc:14769
#4  0x00000000004ed3df in X86_Intel_printInst (MI=0x7fffffffdcd0, O=0x7fffffffdac0, Info=0x988af0) at arch/X86/X86IntelInstPrinter.c:501
#5  0x00000000004015b6 in cs_disasm (ud=0x988a30, buffer=0x988d83 "b\303uA", <incomplete sequence \320>, size=0x6, offset=0x3, count=0x0, 
    insn=0x7fffffffe0a8) at cs.c:513
#6  0x0000000000400ab2 in main ()
#7  0x0000000000502a23 in __libc_start_main ()
#8  0x0000000000400889 in _start ()
```

I haven't investigated the issue extensively, but it looks like the RegNo variable being passed to printRegName (and then to getRegisterName) shouldn't ever be null since getRegisterName contains...

```
return AsmStrs+RegAsmOffset[RegNo-1];
```

This results in a value being read from just before the array (out of bounds read) and a crash.

**Comment by aquynh** [comment]
you can consider using the "next" branch, which does not have this issue.
the "next" branch will be released as v4.0 in the future, an it is pretty stable.
