### ISSUE TITLE
 MemorySanitizer: use-of-uninitialized-value arch/X86/X86DisassemblerDecoder.c:491:8 in readPrefixes

### ISSUE THREAD

**Issue by ghost** [capstone-engine/capstone#729]
``` sh
==2043==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7f09f770802d in readPrefixes /home/fuzzer/Fuzzers/capstone-next/arch/X86/X86DisassemblerDecoder.c:491:8
    #1 0x7f09f770698b in decodeInstruction /home/fuzzer/Fuzzers/capstone-next/arch/X86/X86DisassemblerDecoder.c:2344:6
    #2 0x7f09f774583d in X86_getInstruction /home/fuzzer/Fuzzers/capstone-next/arch/X86/X86Disassembler.c:940:9
    #3 0x7f09f6e8f7cf in cs_disasm /home/fuzzer/Fuzzers/capstone-next/cs.c:654:7
    #4 0x48d401 in LLVMFuzzerTestOneInput (/home/fuzzer/Fuzzers/capstone_fuzzer+0x48d401)
    #5 0x494b4c in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /home/fuzzer/Fuzzers/Fuzzer/FuzzerLoop.cpp:488:13
    #6 0x494390 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long) /home/fuzzer/Fuzzers/Fuzzer/FuzzerLoop.cpp:444:3
    #7 0x494c02 in fuzzer::Fuzzer::RunOneAndUpdateCorpus(unsigned char const*, unsigned long) /home/fuzzer/Fuzzers/Fuzzer/FuzzerLoop.cpp:465:7
    #8 0x4960a3 in fuzzer::Fuzzer::MutateAndTestOne() /home/fuzzer/Fuzzers/Fuzzer/FuzzerLoop.cpp:678:5
    #9 0x496607 in fuzzer::Fuzzer::Loop() /home/fuzzer/Fuzzers/Fuzzer/FuzzerLoop.cpp:766:5
    #10 0x48f7f2 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /home/fuzzer/Fuzzers/Fuzzer/FuzzerDriver.cpp:416:5
    #11 0x49a050 in main /home/fuzzer/Fuzzers/Fuzzer/FuzzerMain.cpp:21:10
    #12 0x7f09f5bcdabf in __libc_start_main /build/glibc-qbmteM/glibc-2.21/csu/libc-start.c:289
    #13 0x41b868 in _start (/home/fuzzer/Fuzzers/capstone_fuzzer+0x41b868)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /home/fuzzer/Fuzzers/capstone-next/arch/X86/X86DisassemblerDecoder.c:491:8 in readPrefixes

Base64: Jyq0Kiq/zSnCJ9chKvg6JzohyiopiK4nKiHnOrSbhgIlOyEoyVhIOgSXFygEtyELKqEp4OcoOychtFch2ykhIQ==


```

**Comment by aquynh** [comment]
which branch is it?

**Comment by revskills** [comment]
next

**Comment by aquynh** [comment]
this looks like a false positive to me, as at this line https://github.com/aquynh/capstone/blob/next/arch/X86/X86DisassemblerDecoder.c#L491, `byte` is always initialized. 

does your fuzzer provide any input triggering this issue?

**Comment by revskills** [comment]
not sure if a false positive, you have a base64 encoded input above.

**Comment by aquynh** [comment]
at https://github.com/aquynh/capstone/blob/next/arch/X86/X86DisassemblerDecoder.c#L480, `byte` is initialized with value 0, so this looks like a false positive to me.

**Comment by radare** [comment]
ConsumeByte is the real initializer which can grab uninitialized memory and result in this issue. Did u even tried to test the input provided by @revskills?
