### ISSUE TITLE
MemorySanitizer: use-of-uninitialized-value arch/AArch64/AArch64GenDisassemblerTables.inc:12742:1 in decodeInstruction

### ISSUE THREAD

**Issue by ghost** [capstone-engine/capstone#730]
``` sh
==2094==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7f7ce1571a5f in decodeInstruction /home/fuzzer/Fuzzers/capstone-next/arch/AArch64/AArch64GenDisassemblerTables.inc:12742:1
    #1 0x7f7ce1570755 in _getInstruction /home/fuzzer/Fuzzers/capstone-next/arch/AArch64/AArch64Disassembler.c:249:11
    #2 0x7f7ce156f439 in AArch64_getInstruction /home/fuzzer/Fuzzers/capstone-next/arch/AArch64/AArch64Disassembler.c:263:24
    #3 0x7f7ce12ec7cf in cs_disasm /home/fuzzer/Fuzzers/capstone-next/cs.c:654:7
    #4 0x48d3b4 in LLVMFuzzerTestOneInput (/home/fuzzer/Fuzzers/capstone_fuzzerARM64+0x48d3b4)
    #5 0x4946ac in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /home/fuzzer/Fuzzers/Fuzzer/FuzzerLoop.cpp:488:13
    #6 0x493ef0 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long) /home/fuzzer/Fuzzers/Fuzzer/FuzzerLoop.cpp:444:3
    #7 0x494762 in fuzzer::Fuzzer::RunOneAndUpdateCorpus(unsigned char const*, unsigned long) /home/fuzzer/Fuzzers/Fuzzer/FuzzerLoop.cpp:465:7
    #8 0x495c03 in fuzzer::Fuzzer::MutateAndTestOne() /home/fuzzer/Fuzzers/Fuzzer/FuzzerLoop.cpp:678:5
    #9 0x496167 in fuzzer::Fuzzer::Loop() /home/fuzzer/Fuzzers/Fuzzer/FuzzerLoop.cpp:766:5
    #10 0x48f352 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /home/fuzzer/Fuzzers/Fuzzer/FuzzerDriver.cpp:416:5
    #11 0x499bb0 in main /home/fuzzer/Fuzzers/Fuzzer/FuzzerMain.cpp:21:10
    #12 0x7f7ce002aabf in __libc_start_main /build/glibc-qbmteM/glibc-2.21/csu/libc-start.c:289
    #13 0x41b838 in _start (/home/fuzzer/Fuzzers/capstone_fuzzerARM64+0x41b838)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /home/fuzzer/Fuzzers/capstone-next/arch/AArch64/AArch64GenDisassemblerTables.inc:12742:1 in decodeInstruction

Base64:U+QtKUEnIQdRKuE6J+gnKScheTsBHii0KXD7O1OdHYnVJyjZJyEo4BcZG9AE4ycpKV0oITspKSc3ISeIlDtJJw==

```

**Comment by aquynh** [comment]
this points to issue at
https://github.com/aquynh/capstone/blob/next/arch/AArch64/AArch64GenDisassemblerTables.inc#L12742,
which is a macro, so i cannot see exactly where this happens. is there a
better clue?

**Comment by radare** [comment]
Macros usually bad for code maintainance, but i guess that trying theinput provided and using a debugger may help to understand the problem

**Comment by aquynh** [comment]
@revskills, do you mind sending a PR to include your ASAN setup into Capstone, so it is easier for everybody to compile in the same way to confirm issues? thanks.

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
