### ISSUE TITLE
Global out of bounds read in SStream_concat0()

### ISSUE THREAD

**Issue by fumfel** [capstone-engine/capstone#879]
**Global out of bounds read in SStream_concat0()**

Tested on Git HEAD: 85f4b8f7d9314bb73c06367ff83c3b46c3ea9433

[Payload](https://github.com/aquynh/capstone/files/867347/crash-bc689419672736cb5e79c6b492d630f5db059346.txt)

Fuzzer - https://gist.github.com/fumfel/47f7656df8bed04885556d5a941898c6

To reproduce: `./capstone_fuzzer crash-bc689419672736cb5e79c6b492d630f5db059346`

ASAN:

```
==15181==ERROR: AddressSanitizer: global-buffer-overflow on address 0x000000c04c1f at pc 0x00000042f57c bp 0x7fff1fedb6c0 sp 0x7fff1fedae68
READ of size 1 at 0x000000c04c1f thread T0
    #0 0x42f57b in strlen (XYZ/capstone_test/capstone_fuzzer+0x42f57b)
    #1 0x4fd897 in SStream_concat0 XYZ/capstone/SStream.c:34:36
    #2 0x6682ce in printInstruction XYZ/capstone/arch/X86/X86GenAsmWriter1.inc:13845:5
    #3 0x667891 in X86_Intel_printInst XYZ/capstone/arch/X86/X86IntelInstPrinter.c:501:3
    #4 0x4f8872 in cs_disasm XYZ/capstone/cs.c:551:4
    #5 0x4f7383 in LLVMFuzzerTestOneInput XYZ/capstone_fuzzer.cc:124:18
    #6 0x6a8e43 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) XYZ/./Fuzzer/FuzzerLoop.cpp:451:13
    #7 0x6a9070 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long) XYZ/./Fuzzer/FuzzerLoop.cpp:408:3
    #8 0x69ebc1 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) XYZ/./Fuzzer/FuzzerDriver.cpp:268:6
    #9 0x6a17de in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) XYZ/./Fuzzer/FuzzerDriver.cpp:585:9
    #10 0x69e930 in main XYZ/./Fuzzer/FuzzerMain.cpp:20:10
    #11 0x7f58ce66882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #12 0x41c438 in _start (XYZ/capstone_test/capstone_fuzzer+0x41c438)

0x000000c04c1f is located 1 bytes to the left of global variable 'AsmStrs' defined in 'arch/X86/X86GenAsmWriter1.inc:12559:15' (0xc04c20) of size 12698
0x000000c04c1f is located 235 bytes to the right of global variable 'AsmStrs' defined in 'arch/X86/X86GenAsmWriter1.inc:14789:15' (0xc04740) of size 1012
SUMMARY: AddressSanitizer: global-buffer-overflow (XYZ/capstone_test/capstone_fuzzer+0x42f57b) in strlen
Shadow bytes around the buggy address:
  0x000080178930: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x000080178940: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x000080178950: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x000080178960: 00 00 00 00 00 00 04 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x000080178970: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
=>0x000080178980: f9 f9 f9[f9]00 00 00 00 00 00 00 00 00 00 00 00
  0x000080178990: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0000801789a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0000801789b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0000801789c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0000801789d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==15181==ABORTING
```

**Comment by aquynh** [comment]
Can you please provide the related input here, so i can verify this with
cstool?

**Comment by fumfel** [comment]
Python wrapper:
```
import subprocess

payload = '7f007f011351004e5530717fff007fff30797334fd62f305401fdbffd356ffe630fd62f320401fe2'
subprocess.call(['cstool','x64', payload, '0x1000'])
```

**Comment by aquynh** [comment]
are you using "master", or "next" branch?

**Comment by fumfel** [comment]
AFAIR problem exists in both branches.

**Comment by aquynh** [comment]
Which OS are you using?

**Comment by fumfel** [comment]
Ubuntu 16.04 x64
Compiler: Clang 5.0 + libfuzzer

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
